default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: pet_adoption_development


test:
  <<: *default
  database: pet_adoption_test

production:
  <<: *default
  database: pet_adoption_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
